GET http://localhost:3333/deliveries/ HTTP/1.1
authorization: Bearer 
###
GET http://localhost:3333/deliveries/1 HTTP/1.1
authorization: Bearer 
###
POST http://localhost:3333/deliveries/ HTTP/1.1
content-type: application/json
authorization: Bearer 

{
  "product": "Pack of Example",
  "recipient_id": 1,
  "deliveryman_id": 2
}
###
PUT http://localhost:3333/deliveries/1 HTTP/1.1
content-type: application/json
authorization: Bearer 

{
  "product": "Pack of Example",
  "recipient_id": 1,
  "deliveryman_id": 1
}
###
DELETE http://localhost:3333/deliveries/2 HTTP/1.1
authorization: Bearer 
###