// index 
GET http://localhost:3333/deliverymans? HTTP/1.1
authorization: Bearer 

### store
POST http://localhost:3333/deliverymans HTTP/1.1
content-type: application/json
authorization: Bearer 

{
  "name": "Jane Doe",
  "avatar_id": "1",
  "email": "jane@example.com",
  "user_id": 2
}

### Update
PUT http://localhost:3333/deliverymans/1 HTTP/1.1
content-type: application/json
authorization: Bearer 

{
  "name": "John Doe",
  "email": "jhon@example.com"
}

###
// Destroy
DELETE http://localhost:3333/deliverymans/1 HTTP/1.1
authorization: Bearer 