GET http://localhost:3333/delivery/ HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE4NTA5Njc4LCJleHAiOjE2MTkxMTQ0Nzh9.87k4cmbpHCulSfAAB0TPmbqPRksbAnZYOLRv9EM68kc
###
GET http://localhost:3333/delivery/1 HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE4NTA5Njc4LCJleHAiOjE2MTkxMTQ0Nzh9.87k4cmbpHCulSfAAB0TPmbqPRksbAnZYOLRv9EM68kc
###
POST http://localhost:3333/delivery/ HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE4NTA5Njc4LCJleHAiOjE2MTkxMTQ0Nzh9.87k4cmbpHCulSfAAB0TPmbqPRksbAnZYOLRv9EM68kc

{
  "product": "Pack of Example",
  "recipient_id": 1,
  "deliveryman_id": 1
}
###
PUT http://localhost:3333/delivery/1 HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE4NTA5Njc4LCJleHAiOjE2MTkxMTQ0Nzh9.87k4cmbpHCulSfAAB0TPmbqPRksbAnZYOLRv9EM68kc

{
  "product": "Pack of Example",
  "recipient_id": 1,
  "deliveryman_id": 1
}
###
DELETE http://localhost:3333/delivery/2 HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE4NTA5Njc4LCJleHAiOjE2MTkxMTQ0Nzh9.87k4cmbpHCulSfAAB0TPmbqPRksbAnZYOLRv9EM68kc
###