GET http://localhost:3333/deliveries/ HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIwNDQ3MjIxLCJleHAiOjE2MjEwNTIwMjF9.XboxBvI1KOJY2QATfgcjEWIL8kkj0r4K18r_l94gqiM
###
GET http://localhost:3333/deliveries/1 HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIwNDQ3MjIxLCJleHAiOjE2MjEwNTIwMjF9.XboxBvI1KOJY2QATfgcjEWIL8kkj0r4K18r_l94gqiM
###
POST http://localhost:3333/deliveries/ HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIwNDQ3MjIxLCJleHAiOjE2MjEwNTIwMjF9.XboxBvI1KOJY2QATfgcjEWIL8kkj0r4K18r_l94gqiM

{
  "product": "Pack of Example",
  "recipient_id": 1,
  "deliveryman_id": 2
}
###
PUT http://localhost:3333/deliveries/1 HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIwNDQ3MjIxLCJleHAiOjE2MjEwNTIwMjF9.XboxBvI1KOJY2QATfgcjEWIL8kkj0r4K18r_l94gqiM

{
  "product": "Pack of Example",
  "recipient_id": 1,
  "deliveryman_id": 1
}
###
DELETE http://localhost:3333/deliveries/2 HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIwNDQ3MjIxLCJleHAiOjE2MjEwNTIwMjF9.XboxBvI1KOJY2QATfgcjEWIL8kkj0r4K18r_l94gqiM
###