// Método Index
GET http://localhost:3333/recipients
###
// Métodod Store
POST http://localhost:3333/users HTTP/1.1
content-type: application/json

{
  "name": "Thales Monteiro",
  "rua": "Estr. Prof. Daltro Santos",
  "numero": 5,
  "complemento": "Casa 3",
  "estado": "RJ",
  "cidade": "Rio de Janeiro",
  "cep": "23092-205",
}
###